// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ShiftAssignerServer.Tests.Features.MultiTenant
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Multi_TenantRegistrationAndWorkerManagementFeature : object, global::Xunit.IClassFixture<Multi_TenantRegistrationAndWorkerManagementFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/MultiTenant", "Multi-Tenant Registration and Worker Management", "  In order to ensure multi-tenant functionality works correctly\r\n  As a client of" +
                " the API\r\n  I want to register multiple tenants with their shift leaders and wor" +
                "kers, and test worker reassignment", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MultiTenantRegistrationAndManagement.feature"
#line hidden
        
        public Multi_TenantRegistrationAndWorkerManagementFeature(Multi_TenantRegistrationAndWorkerManagementFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/MultiTenant/MultiTenantRegistrationAndManagement.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register two tenants with shift leaders and workers")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Multi-Tenant Registration and Worker Management")]
        [global::Xunit.TraitAttribute("Description", "Register two tenants with shift leaders and workers")]
        [global::Xunit.TraitAttribute("Category", "integration")]
        [global::Xunit.TraitAttribute("Category", "registration")]
        [global::Xunit.TraitAttribute("Category", "multi-tenant")]
        public async global::System.Threading.Tasks.Task RegisterTwoTenantsWithShiftLeadersAndWorkers()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "registration",
                    "multi-tenant"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register two tenants with shift leaders and workers", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await testRunner.GivenAsync("I have tenant boss registration payloads for multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
  await testRunner.WhenAsync("I register tenant \"1\" for multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
  await testRunner.ThenAsync("the tenant \"1\" registration response should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
  await testRunner.WhenAsync("I register tenant \"2\" for multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
  await testRunner.ThenAsync("the tenant \"2\" registration response should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
  await testRunner.WhenAsync("I register shiftleader \"leader-1\" for tenant \"1\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
  await testRunner.ThenAsync("the shiftleader \"leader-1\" registration for tenant \"1\" should contain a JWT token" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 19
  await testRunner.WhenAsync("I register shiftleader \"leader-2\" for tenant \"1\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
  await testRunner.ThenAsync("the shiftleader \"leader-2\" registration for tenant \"1\" should contain a JWT token" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
  await testRunner.WhenAsync("I register shiftleader \"leader-3\" for tenant \"2\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
  await testRunner.ThenAsync("the shiftleader \"leader-3\" registration for tenant \"2\" should contain a JWT token" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
  await testRunner.WhenAsync("shiftleader \"leader-1\" logs in for tenant \"1\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
  await testRunner.ThenAsync("the shiftleader \"leader-1\" login for tenant \"1\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
  await testRunner.WhenAsync("shiftleader \"leader-2\" logs in for tenant \"1\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
  await testRunner.ThenAsync("the shiftleader \"leader-2\" login for tenant \"1\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
  await testRunner.WhenAsync("shiftleader \"leader-3\" logs in for tenant \"2\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
  await testRunner.ThenAsync("the shiftleader \"leader-3\" login for tenant \"2\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
  await testRunner.WhenAsync("shiftleader \"leader-1\" registers worker \"worker-1\" for tenant \"1\" in multi tenant" +
                        " flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
  await testRunner.ThenAsync("the worker registration for tenant \"1\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
  await testRunner.ThenAsync("I verify that shiftleader \"leader-1\" has worker \"worker-1\" assigned for tenant \"1" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
  await testRunner.WhenAsync("shiftleader \"leader-1\" registers worker \"worker-4\" for tenant \"1\" in multi tenant" +
                        " flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
  await testRunner.ThenAsync("the worker registration for tenant \"1\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 40
  await testRunner.ThenAsync("I verify that shiftleader \"leader-1\" has worker \"worker-4\" assigned for tenant \"1" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
  await testRunner.WhenAsync("shiftleader \"leader-1\" registers worker \"worker-5\" for tenant \"1\" in multi tenant" +
                        " flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
  await testRunner.ThenAsync("the worker registration for tenant \"1\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 44
  await testRunner.ThenAsync("I verify that shiftleader \"leader-1\" has worker \"worker-5\" assigned for tenant \"1" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
  await testRunner.WhenAsync("shiftleader \"leader-2\" registers worker \"worker-2\" for tenant \"1\" in multi tenant" +
                        " flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
  await testRunner.ThenAsync("the worker registration for tenant \"1\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
  await testRunner.ThenAsync("I verify that shiftleader \"leader-2\" has worker \"worker-2\" assigned for tenant \"1" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
  await testRunner.WhenAsync("shiftleader \"leader-3\" registers worker \"worker-3\" for tenant \"2\" in multi tenant" +
                        " flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
  await testRunner.ThenAsync("the worker registration for tenant \"2\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
  await testRunner.ThenAsync("I verify that shiftleader \"leader-3\" has worker \"worker-3\" assigned for tenant \"2" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
  await testRunner.WhenAsync("worker \"worker-1\" logs in for tenant \"1\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
  await testRunner.ThenAsync("the worker \"worker-1\" login for tenant \"1\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 57
  await testRunner.WhenAsync("worker \"worker-2\" logs in for tenant \"1\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
  await testRunner.ThenAsync("the worker \"worker-2\" login for tenant \"1\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 60
  await testRunner.WhenAsync("worker \"worker-3\" logs in for tenant \"2\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
  await testRunner.ThenAsync("the worker \"worker-3\" login for tenant \"2\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 63
  await testRunner.WhenAsync("worker \"worker-4\" logs in for tenant \"1\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
  await testRunner.ThenAsync("the worker \"worker-4\" login for tenant \"1\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 66
  await testRunner.WhenAsync("worker \"worker-5\" logs in for tenant \"1\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
  await testRunner.ThenAsync("the worker \"worker-5\" login for tenant \"1\" should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 70
  await testRunner.WhenAsync("shift leader \"leader-1\" reassigns worker \"worker-1\" to shift leader \"leader-2\" fo" +
                        "r tenant \"1\" in multi tenant flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
  await testRunner.ThenAsync("shift leader \"leader-1\" should have \"2\" workers assigned for tenant \"1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
  await testRunner.ThenAsync("shift leader \"leader-2\" should have \"2\" workers assigned for tenant \"1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Multi_TenantRegistrationAndWorkerManagementFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await Multi_TenantRegistrationAndWorkerManagementFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
