// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ShiftAssignerServer.Tests.Features.SingleTenant
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WorkerRegistrationValidationFeature : object, global::Xunit.IClassFixture<WorkerRegistrationValidationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/SingleTenant", "Worker Registration Validation", "  In order to ensure data integrity\r\n  As a system administrator\r\n  I want to val" +
                "idate all worker registration requests", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WorkerRegistrationValidation.feature"
#line hidden
        
        public WorkerRegistrationValidationFeature(WorkerRegistrationValidationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("I have a tenant boss registration payload", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("Tenant registration \"validation-tenant-1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("the response should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
    await testRunner.WhenAsync("I create a shift leader with id \"validation-leader-1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
    await testRunner.ThenAsync("the response should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/SingleTenant/WorkerRegistrationValidation.feature.ndjson", 21);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Valid worker registration should succeed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Valid worker registration should succeed")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        public async global::System.Threading.Tasks.Task ValidWorkerRegistrationShouldSucceed()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Valid worker registration should succeed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "ID",
                            "worker-valid-001"});
                table1.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table1.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table1.AddRow(new string[] {
                            "PhoneNumber",
                            "+1-555-123-4567"});
                table1.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table1.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table1.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 15
    await testRunner.WhenAsync("I register a worker with valid data", ((string)(null)), table1, "When ");
#line hidden
#line 24
    await testRunner.ThenAsync("the worker registration should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
    await testRunner.AndAsync("the response should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration without ID should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration without ID should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithoutIDShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration without ID should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "ID",
                            ""});
                table2.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table2.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table2.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table2.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table2.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table2.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 29
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table2, "When ");
#line hidden
#line 38
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
    await testRunner.AndAsync("the validation error should contain \"ID is required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with short ID should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with short ID should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithShortIDShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with short ID should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table3.AddRow(new string[] {
                            "ID",
                            "ab"});
                table3.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table3.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table3.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table3.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table3.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table3.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 43
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table3, "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 53
    await testRunner.AndAsync("the validation error should contain \"ID must be at least 3 characters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with ID containing special characters should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with ID containing special characters should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithIDContainingSpecialCharactersShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with ID containing special characters should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table4.AddRow(new string[] {
                            "ID",
                            "worker@123#$"});
                table4.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table4.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table4.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table4.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table4.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table4.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 57
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table4, "When ");
#line hidden
#line 66
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
    await testRunner.AndAsync("the validation error should contain \"ID must contain only alphanumeric characters" +
                        ", hyphens, or underscores\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration without FirstName should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration without FirstName should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithoutFirstNameShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration without FirstName should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table5.AddRow(new string[] {
                            "ID",
                            "worker-002"});
                table5.AddRow(new string[] {
                            "FirstName",
                            ""});
                table5.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table5.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table5.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table5.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table5.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 71
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table5, "When ");
#line hidden
#line 80
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 81
    await testRunner.AndAsync("the validation error should contain \"FirstName is required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration without LastName should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration without LastName should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithoutLastNameShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration without LastName should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 84
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table6.AddRow(new string[] {
                            "ID",
                            "worker-003"});
                table6.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table6.AddRow(new string[] {
                            "LastName",
                            ""});
                table6.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table6.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table6.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table6.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 85
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table6, "When ");
#line hidden
#line 94
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 95
    await testRunner.AndAsync("the validation error should contain \"LastName is required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with FirstName containing numbers should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with FirstName containing numbers should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithFirstNameContainingNumbersShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with FirstName containing numbers should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 98
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table7.AddRow(new string[] {
                            "ID",
                            "worker-004"});
                table7.AddRow(new string[] {
                            "FirstName",
                            "John123"});
                table7.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table7.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table7.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table7.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table7.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 99
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table7, "When ");
#line hidden
#line 108
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 109
    await testRunner.AndAsync("the validation error should contain \"Names must not contain numbers or special ch" +
                        "aracters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with LastName containing special characters should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with LastName containing special characters should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithLastNameContainingSpecialCharactersShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with LastName containing special characters should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 112
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table8.AddRow(new string[] {
                            "ID",
                            "worker-005"});
                table8.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table8.AddRow(new string[] {
                            "LastName",
                            "Doe@123"});
                table8.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table8.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table8.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table8.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 113
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table8, "When ");
#line hidden
#line 122
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 123
    await testRunner.AndAsync("the validation error should contain \"Names must not contain numbers or special ch" +
                        "aracters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration without PhoneNumber should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration without PhoneNumber should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithoutPhoneNumberShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration without PhoneNumber should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 126
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table9.AddRow(new string[] {
                            "ID",
                            "worker-006"});
                table9.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table9.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table9.AddRow(new string[] {
                            "PhoneNumber",
                            ""});
                table9.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table9.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table9.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 127
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table9, "When ");
#line hidden
#line 136
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 137
    await testRunner.AndAsync("the validation error should contain \"PhoneNumber is required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with invalid PhoneNumber format should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with invalid PhoneNumber format should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithInvalidPhoneNumberFormatShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with invalid PhoneNumber format should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 140
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table10.AddRow(new string[] {
                            "ID",
                            "worker-007"});
                table10.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table10.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table10.AddRow(new string[] {
                            "PhoneNumber",
                            "ABC-DEF-GHIJ"});
                table10.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table10.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table10.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 141
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table10, "When ");
#line hidden
#line 150
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 151
    await testRunner.AndAsync("the validation error should contain \"PhoneNumber must contain only digits\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with age below 16 should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with age below 16 should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithAgeBelow16ShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with age below 16 should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 154
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table11.AddRow(new string[] {
                            "ID",
                            "worker-008"});
                table11.AddRow(new string[] {
                            "FirstName",
                            "Young"});
                table11.AddRow(new string[] {
                            "LastName",
                            "Person"});
                table11.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table11.AddRow(new string[] {
                            "DateOfBirth",
                            "2015-01-01"});
                table11.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table11.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 155
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table11, "When ");
#line hidden
#line 164
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 165
    await testRunner.AndAsync("the validation error should contain \"Person must be at least 16 years old\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with age above 100 should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with age above 100 should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithAgeAbove100ShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with age above 100 should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 168
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table12.AddRow(new string[] {
                            "ID",
                            "worker-009"});
                table12.AddRow(new string[] {
                            "FirstName",
                            "Old"});
                table12.AddRow(new string[] {
                            "LastName",
                            "Person"});
                table12.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table12.AddRow(new string[] {
                            "DateOfBirth",
                            "1900-01-01"});
                table12.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table12.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 169
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table12, "When ");
#line hidden
#line 178
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 179
    await testRunner.AndAsync("the validation error should contain \"not older than 100 years\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with short password should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with short password should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithShortPasswordShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with short password should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 182
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table13.AddRow(new string[] {
                            "ID",
                            "worker-010"});
                table13.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table13.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table13.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table13.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table13.AddRow(new string[] {
                            "PasswordHash",
                            "12345"});
                table13.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 183
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table13, "When ");
#line hidden
#line 192
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 193
    await testRunner.AndAsync("the validation error should contain \"Password must be at least 6 characters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration without ShiftLeaderId should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration without ShiftLeaderId should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithoutShiftLeaderIdShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration without ShiftLeaderId should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 196
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table14.AddRow(new string[] {
                            "ID",
                            "worker-011"});
                table14.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table14.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table14.AddRow(new string[] {
                            "PhoneNumber",
                            "555-1234"});
                table14.AddRow(new string[] {
                            "DateOfBirth",
                            "2000-01-15"});
                table14.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass123"});
                table14.AddRow(new string[] {
                            "ShiftLeaderId",
                            ""});
#line 197
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table14, "When ");
#line hidden
#line 206
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 207
    await testRunner.AndAsync("the validation error should contain \"ShiftLeaderId is required when registering a" +
                        " worker\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with multiple validation errors should fail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with multiple validation errors should fail")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        [global::Xunit.TraitAttribute("Category", "negative")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithMultipleValidationErrorsShouldFail()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration",
                    "negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with multiple validation errors should fail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 210
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table15.AddRow(new string[] {
                            "ID",
                            ""});
                table15.AddRow(new string[] {
                            "FirstName",
                            "John123"});
                table15.AddRow(new string[] {
                            "LastName",
                            ""});
                table15.AddRow(new string[] {
                            "PhoneNumber",
                            ""});
                table15.AddRow(new string[] {
                            "DateOfBirth",
                            "2015-01-01"});
                table15.AddRow(new string[] {
                            "PasswordHash",
                            "123"});
                table15.AddRow(new string[] {
                            "ShiftLeaderId",
                            ""});
#line 211
    await testRunner.WhenAsync("I register a worker with invalid data", ((string)(null)), table15, "When ");
#line hidden
#line 220
    await testRunner.ThenAsync("the worker registration should fail with validation errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 221
    await testRunner.AndAsync("the validation should contain multiple errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 222
    await testRunner.AndAsync("the validation error should contain \"ID is required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 223
    await testRunner.AndAsync("the validation error should contain \"LastName is required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 224
    await testRunner.AndAsync("the validation error should contain \"PhoneNumber is required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 225
    await testRunner.AndAsync("the validation error should contain \"Password must be at least 6 characters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 226
    await testRunner.AndAsync("the validation error should contain \"ShiftLeaderId is required when registering a" +
                        " worker\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 227
    await testRunner.AndAsync("the validation error should contain \"Names must not contain numbers\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with valid international phone number should succeed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with valid international phone number should succeed")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithValidInternationalPhoneNumberShouldSucceed()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with valid international phone number should succeed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 230
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table16.AddRow(new string[] {
                            "ID",
                            "worker-intl-001"});
                table16.AddRow(new string[] {
                            "FirstName",
                            "Maria"});
                table16.AddRow(new string[] {
                            "LastName",
                            "Garcia"});
                table16.AddRow(new string[] {
                            "PhoneNumber",
                            "+34-91-123-4567"});
                table16.AddRow(new string[] {
                            "DateOfBirth",
                            "1995-06-20"});
                table16.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass456"});
                table16.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 231
    await testRunner.WhenAsync("I register a worker with valid data", ((string)(null)), table16, "When ");
#line hidden
#line 240
    await testRunner.ThenAsync("the worker registration should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 241
    await testRunner.AndAsync("the response should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with hyphenated name should succeed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with hyphenated name should succeed")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithHyphenatedNameShouldSucceed()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with hyphenated name should succeed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 244
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table17.AddRow(new string[] {
                            "ID",
                            "worker-hyphen-001"});
                table17.AddRow(new string[] {
                            "FirstName",
                            "Mary-Anne"});
                table17.AddRow(new string[] {
                            "LastName",
                            "Smith-Jones"});
                table17.AddRow(new string[] {
                            "PhoneNumber",
                            "555-9999"});
                table17.AddRow(new string[] {
                            "DateOfBirth",
                            "1990-03-10"});
                table17.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass789"});
                table17.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 245
    await testRunner.WhenAsync("I register a worker with valid data", ((string)(null)), table17, "When ");
#line hidden
#line 254
    await testRunner.ThenAsync("the worker registration should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 255
    await testRunner.AndAsync("the response should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration with name containing apostrophe should succeed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration with name containing apostrophe should succeed")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationWithNameContainingApostropheShouldSucceed()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration with name containing apostrophe should succeed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 258
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table18.AddRow(new string[] {
                            "ID",
                            "worker-apos-001"});
                table18.AddRow(new string[] {
                            "FirstName",
                            "Sean"});
                table18.AddRow(new string[] {
                            "LastName",
                            "O\'Brien"});
                table18.AddRow(new string[] {
                            "PhoneNumber",
                            "555-8888"});
                table18.AddRow(new string[] {
                            "DateOfBirth",
                            "1988-12-25"});
                table18.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass000"});
                table18.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 259
    await testRunner.WhenAsync("I register a worker with valid data", ((string)(null)), table18, "When ");
#line hidden
#line 268
    await testRunner.ThenAsync("the worker registration should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 269
    await testRunner.AndAsync("the response should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Worker registration at minimum age (16 years) should succeed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker Registration Validation")]
        [global::Xunit.TraitAttribute("Description", "Worker registration at minimum age (16 years) should succeed")]
        [global::Xunit.TraitAttribute("Category", "validation")]
        [global::Xunit.TraitAttribute("Category", "worker-registration")]
        public async global::System.Threading.Tasks.Task WorkerRegistrationAtMinimumAge16YearsShouldSucceed()
        {
            string[] tagsOfScenario = new string[] {
                    "validation",
                    "worker-registration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Worker registration at minimum age (16 years) should succeed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 272
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table19.AddRow(new string[] {
                            "ID",
                            "worker-min-age-001"});
                table19.AddRow(new string[] {
                            "FirstName",
                            "Young"});
                table19.AddRow(new string[] {
                            "LastName",
                            "Worker"});
                table19.AddRow(new string[] {
                            "PhoneNumber",
                            "555-7777"});
                table19.AddRow(new string[] {
                            "DateOfBirth",
                            "2008-11-28"});
                table19.AddRow(new string[] {
                            "PasswordHash",
                            "SecurePass111"});
                table19.AddRow(new string[] {
                            "ShiftLeaderId",
                            "validation-leader-1"});
#line 273
    await testRunner.WhenAsync("I register a worker with valid data", ((string)(null)), table19, "When ");
#line hidden
#line 282
    await testRunner.ThenAsync("the worker registration should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 283
    await testRunner.AndAsync("the response should contain a JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await WorkerRegistrationValidationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await WorkerRegistrationValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
