using ShiftAssignerServer.Models.Stuff;
using ShiftAssignerServer.Models.WorkerScheduling;
using ShiftAssignerServer.Repositories;
using ShiftAssignerServer.Requests;

namespace ShiftAssignerServer.Services;

public interface IWorkerSchedulerService
{
    Task<bool> CreateNewWorkerRegisteringRequest(CreateShiftPeriodSchedulingRequest request, string shiftLeaderId);

}

public class WorkerSchedulerService : IWorkerSchedulerService
{
    private readonly ITenantUnitOfWork _tenantUnitOfWork;

    public WorkerSchedulerService(ITenantUnitOfWork tenantUnitOfWork)
    {
        _tenantUnitOfWork = tenantUnitOfWork;
    }

    public async Task<bool> CreateNewWorkerRegisteringRequest(CreateShiftPeriodSchedulingRequest request, string shiftLeaderId)
    {
        var config = await _tenantUnitOfWork.ShiftPeriodSchedulingRepository.GetAllAsync(x => x.IsActive && x.ShiftLeaderId.Equals(shiftLeaderId));

        var record = new ShiftPeriodScheduling 
        {
            // Id is auto-generated by database
            ShiftLeaderId = shiftLeaderId,
            StartFrom = request.StartFrom,
            IsActive = true,
            Period = request.NextPeriod.Select(dayRequest => new ShiftPeriodScheduling.Day
            {
                DateOnly = dayRequest.Date,
                Shifts = dayRequest.Shifts.Select(shiftRequest => new ShiftPeriodScheduling.Day.ShiftInfo
                {
                    ShiftName = shiftRequest.ShiftName,
                    AmountOfWorkers = shiftRequest.AmountOfWorkers,
                    WorkerIds = new List<string>() // Initially empty, workers assigned later
                }).ToList()
            }).ToList()
        };

        await _tenantUnitOfWork.ShiftPeriodSchedulingRepository.InsertAsync(record);

        return true;
    }
}