using Microsoft.EntityFrameworkCore.Migrations.Operations;
using ShiftAssignerServer.Models.WorkerScheduling;
using ShiftAssignerServer.Repositories;
using ShiftAssignerServer.Requests;
using ShiftAssignerServer.Services.Validation;

namespace ShiftAssignerServer.Services;

public interface IWorkerSchedulerService
{
    Task<ShiftPeriodScheduling> CreateNewWorkerRegisteringRequest(CreateShiftPeriodSchedulingRequest request, string shiftLeaderId);
    Task<WorkerShiftPeriodSchedulingResponse> GetWorkerShiftPeriodCurrentAndNextScheduling(string workerId);
    Task<WorkerAssigningToPeriodResponse> WorkerSelfAssignToShift(string? workerId, WorkerAssigningToPeriodRequest request);
}

public class WorkerSchedulerService : IWorkerSchedulerService
{
    private readonly ITenantUnitOfWork _tenantUnitOfWork;
    private readonly IWorkerSchedulerValidationService _validationService;

    public WorkerSchedulerService(ITenantUnitOfWork tenantUnitOfWork, IWorkerSchedulerValidationService validationService)
    {
        _tenantUnitOfWork = tenantUnitOfWork;
        _validationService = validationService;
    }

    public async Task<ShiftPeriodScheduling> CreateNewWorkerRegisteringRequest(CreateShiftPeriodSchedulingRequest request, string shiftLeaderId)
    {
        // Validate the request - this will throw ShiftAssignmentException if validation fails
        await _validationService.ValidateCreateShiftPeriodRequestAsync(request, shiftLeaderId);

        var config = await _tenantUnitOfWork.ShiftPeriodSchedulingRepository.GetAllAsync(x => x.IsActive && x.ShiftLeaderId.Equals(shiftLeaderId));

        var record = new ShiftPeriodScheduling
        {
            // Id is auto-generated by database
            ShiftLeaderId = shiftLeaderId,
            StartFrom = request.StartFrom,
            IsActive = true,
            Period = request.NextPeriod.Select(dayRequest => new ShiftPeriodScheduling.Day
            {
                DateOnly = dayRequest.Date,
                Shifts = dayRequest.Shifts.Select(shiftRequest => new ShiftPeriodScheduling.Day.ShiftInfo
                {
                    ShiftName = shiftRequest.ShiftName,
                    AmountOfWorkers = shiftRequest.AmountOfWorkers,
                    WorkerIds = new List<string>() // Initially empty, workers assigned later
                }).ToList()
            }).ToList()
        };

        await _tenantUnitOfWork.ShiftPeriodSchedulingRepository.InsertAsync(record);

        return record;
    }

    public async Task<WorkerShiftPeriodSchedulingResponse> GetWorkerShiftPeriodCurrentAndNextScheduling(string workerId)
    {
        // Get active shift periods where the worker is assigned
        var activeShiftPeriods = await _tenantUnitOfWork.ShiftPeriodSchedulingRepository
            .GetAllAsync(x => x.IsActive &&
                x.Period.Any(day => day.Shifts.Any(shift => shift.WorkerIds.Contains(workerId))));

        if (activeShiftPeriods.IsEmpty())
        {
            return new WorkerShiftPeriodSchedulingResponse
            {
                StartFrom = DateOnly.FromDateTime(DateTime.Now),
                Period = new List<WorkerShiftPeriodSchedulingResponse.CreateDaySchedule>(),
                Message = "No active shift assignments found for worker"
            };
        }

        // Build the response with worker's assigned shifts from all active periods
        var workerDays = new List<WorkerShiftPeriodSchedulingResponse.CreateDaySchedule>();
        foreach (var period in activeShiftPeriods.OrderBy(x => x.StartFrom))
        {
            foreach (var day in period.Period)
            {
                var workerShifts = day.Shifts
                    .Where(shift => shift.WorkerIds.Contains(workerId))
                    .Select(shift => new WorkerShiftPeriodSchedulingResponse.CreateShiftInfo
                    {
                        ShiftName = shift.ShiftName
                    })
                    .ToList();

                if (workerShifts.Any())
                {
                    workerDays.Add(new WorkerShiftPeriodSchedulingResponse.CreateDaySchedule
                    {
                        Date = day.DateOnly,
                        Shifts = workerShifts
                    });
                }
            }
        }

        return new WorkerShiftPeriodSchedulingResponse
        {
            StartFrom = activeShiftPeriods.Min(x => x.StartFrom),
            Period = workerDays.OrderBy(d => d.Date).ToList(),
            Message = "Worker shift schedule retrieved successfully"
        };
    }

    public async Task<WorkerAssigningToPeriodResponse> WorkerSelfAssignToShift(string? workerId, WorkerAssigningToPeriodRequest request)
    {
        // Validate the request - this will throw ShiftAssignmentException if validation fails
        await _validationService.ValidateWorkerAssigningToPeriodRequestAsync(request, workerId);

        var responseShifts = new List<WorkerAssigningToPeriodResponse.CreateDaySchedule>();

        foreach (var requestDay in request.Period)
        {
            var dayShifts = new List<WorkerAssigningToPeriodResponse.CreateShiftInfo>();

            foreach (var requestShift in requestDay.Shifts)
            {
                var shiftAssigned = false;
                var assignmentReason = string.Empty;

                // Find the shift period that contains this date and shift
                var shiftPeriods = await _tenantUnitOfWork.ShiftPeriodSchedulingRepository
                    .GetAllAsync(x => x.IsActive &&
                        x.Period.Any(p => p.DateOnly == requestDay.Date &&
                            p.Shifts.Any(s => s.ShiftName.Equals(requestShift.ShiftName, StringComparison.OrdinalIgnoreCase))));

                var period = shiftPeriods.First();
                var targetDay = period.Period.FirstOrDefault(p => p.DateOnly == requestDay.Date);
                var targetShift = targetDay.Shifts.FirstOrDefault(s =>
                    s.ShiftName.Equals(requestShift.ShiftName, StringComparison.OrdinalIgnoreCase));

                // Check if worker is not already assigned and shift has capacity
                if (!targetShift.WorkerIds.Contains(workerId) && targetShift.WorkerIds.Count < targetShift.AmountOfWorkers)
                {
                    // Assign worker to shift
                    targetShift.WorkerIds.Add(workerId);
                        await _tenantUnitOfWork.ShiftPeriodSchedulingRepository.UpdateAsync(
                            x => x.Id == period.Id, 
                            updatedPeriod => 
                            {
                                var dayToUpdate = updatedPeriod.Period.FirstOrDefault(p => p.DateOnly == requestDay.Date);
                                var shiftToUpdate = dayToUpdate?.Shifts.FirstOrDefault(s => 
                                    s.ShiftName.Equals(requestShift.ShiftName, StringComparison.OrdinalIgnoreCase));
                                if (shiftToUpdate != null && !shiftToUpdate.WorkerIds.Contains(workerId))
                                {
                                    shiftToUpdate.WorkerIds.Add(workerId);
                                }
                            });
                }
                else if (targetShift.WorkerIds.Contains(workerId))
                {
                    assignmentReason = "Worker already assigned to this shift";
                }
                else
                {
                    assignmentReason = $"Shift at full capacity ({targetShift.AmountOfWorkers} workers)";
                }

                dayShifts.Add(new WorkerAssigningToPeriodResponse.CreateShiftInfo
                {
                    ShiftName = requestShift.ShiftName,
                    Assigned = shiftAssigned,
                    Reason = assignmentReason
                });
            }

            responseShifts.Add(new WorkerAssigningToPeriodResponse.CreateDaySchedule
            {
                Date = requestDay.Date,
                Shifts = dayShifts
            });
        }

        return new WorkerAssigningToPeriodResponse
        {
            Period = responseShifts
        };
    }
}